name: run append_headlines.py

on:
  schedule:
    - cron: '* 17 * * *' # Every day at 5 pm
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: get the headlines and append to jsonl file
        uses: prefix-dev/setup-pixi@v0.2.0
        with:
            cache: true
      - run: pixi run python append_headlines.py
          
      - name: commit files
        run: |
          git pull origin main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated headlines" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 